import { type ReactNode, useEffect, useRef, useState } from "react";
import { ArrowRight, BadgeCheck, Brain, Check, ChevronDown, CircleCheck, Eye, Gauge, Layers3, Lightbulb, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, Target, Video, X } from "lucide-react";

import tuMenteEnGPTCover from "@/assets/tu-mente-en-gpt-cover-v2.png.asset.json";
import tuSegundoCerebroCover from "@/assets/tu-segundo-cerebro-cover-v2.png.asset.json";
import tuGemeloDigitalCover from "@/assets/tu-gemelo-digital-cover-v2.png.asset.json";
import elEspejoDigitalCover from "@/assets/el-espejo-digital-cover-v2.png.asset.json";
import depoimento10 from "@/assets/depoimento-10.png.asset.json";
import depoimento11 from "@/assets/depoimento-11.png.asset.json";
import depoimento12 from "@/assets/depoimento-12.png.asset.json";
import depoimento13 from "@/assets/depoimento-13.png.asset.json";
import depoimento14 from "@/assets/depoimento-14.png.asset.json";
import depoimento15 from "@/assets/depoimento-15.png.asset.json";
import heroCover from "@/assets/hero-mente-en-gpt-cena.png.asset.json";
import ofertaComboCompleto from "@/assets/oferta-combo-completo.png.asset.json";
import metodoNovo39 from "@/assets/metodo-novo-39.png.asset.json";
import metodoNovo40 from "@/assets/metodo-novo-40.png.asset.json";
import metodoNovo41 from "@/assets/metodo-novo-41.png.asset.json";
import metodoNovo42 from "@/assets/metodo-novo-42.png.asset.json";
import metodoNovo43 from "@/assets/metodo-novo-43.png.asset.json";
import metodoNovo44 from "@/assets/metodo-novo-44.png.asset.json";

const pilarImagens = [metodoNovo39, metodoNovo40, metodoNovo41, metodoNovo42, metodoNovo43, metodoNovo44];
const depoimentos = [depoimento10, depoimento11, depoimento12, depoimento13, depoimento14, depoimento15];
const faixaItens = ["MÉTODO MENTE EXPANDIDA™", "GUIA PRINCIPAL + BÔNUS GRÁTIS", "PAGAMENTO ÚNICO", "ACESSO IMEDIATO", "GARANTIA DE 7 DIAS", "SUA IA, DO SEU JEITO"];
const typewriterWords = ["CRIAR.", "APRENDER.", "PRODUZIR.", "CONQUISTAR."];

function TypewriterWord() {
  const [wordIndex, setWordIndex] = useState(0);
  const [charCount, setCharCount] = useState(0);
  const [deleting, setDeleting] = useState(false);
  useEffect(() => {
    const word = typewriterWords[wordIndex]!;
    const delay = !deleting ? (charCount < word.length ? 110 : 1700) : (charCount > 0 ? 60 : 350);
    const timer = setTimeout(() => {
      if (!deleting) {
        if (charCount < word.length) setCharCount(charCount + 1); else setDeleting(true);
      } else if (charCount > 0) setCharCount(charCount - 1);
      else { setDeleting(false); setWordIndex((wordIndex + 1) % typewriterWords.length); }
    }, delay);
    return () => clearTimeout(timer);
  }, [charCount, deleting, wordIndex]);
  return <span className="relative inline-flex items-baseline"><span className="opacity-0" aria-hidden>CONQUISTAR.</span><span className="upsell-text-gradient-gold absolute left-1/2 top-0 -translate-x-1/2 whitespace-nowrap" aria-hidden>{typewriterWords[wordIndex]!.slice(0, charCount)}<span className="ml-1 inline-block h-[0.85em] w-[3px] animate-pulse bg-upsell-gold align-baseline" /></span></span>;
}

const problemas = [
  "Você abre o chat e começa do zero. Todos os dias. Em toda conversa.",
  "Perde minutos (e energia) explicando de novo quem você é, o que faz e o que quer conquistar.",
  "Recebe respostas genéricas que poderiam ter sido escritas para qualquer pessoa — menos para você.",
  "Tem boas ideias, mas elas ficam na cabeça porque você não consegue organizar, priorizar nem executar.",
  "Sabe que conteúdo vende, mas não quer passar a vida gravando na frente de uma câmera.",
  "Todo o seu conhecimento está espalhado: notas, chats, ideias… e nenhum sistema transforma isso em resultado.",
];
const beneficiosMente = ["Ensinar à IA quem você é e como trabalha", "Configurar seu tom de voz e suas preferências", "Organizar informações sobre seus produtos e seu público", "Transformar seu conhecimento em uma base consultável", "Receber respostas mais coerentes com seu contexto", "Reduzir correções, repetições e retrabalho", "Criar conteúdos sem apagar sua personalidade", "Ter uma inteligência preparada para começar do lugar certo"];
const beneficiosEspejo = ["Padrões de pensamento que aparecem repetidamente", "Maneiras recorrentes de tomar decisões", "Forças e habilidades que você talvez esteja subestimando", "Possíveis crenças e bloqueios presentes nas suas falas", "Temas que ocupam sua atenção com frequência", "Oportunidades que podem estar diante de você sem serem reconhecidas", "Mudanças que aconteceram ao longo da sua trajetória", "Um verdadeiro “manual da sua mente”"];
const comboItens = [
  { nome: "Tu Mente en GPT", etiqueta: "Guia 1", desc: "Personalize o ChatGPT com seu contexto" },
  { nome: "Tu Segundo Cerebro", etiqueta: "Guia 2", desc: "Pense com mais clareza dentro do ChatGPT" },
  { nome: "Tu Gemelo Digital", etiqueta: "Guia 3", desc: "Transforme ideias em presença digital" },
  { nome: "El Espejo Digital", etiqueta: "Guia 4", desc: "Reflexão guiada com o apoio do ChatGPT" },
];
const pilares = [
  { step: "01", name: "Tu Mente en GPT", tag: "CONHECE", icon: Brain, title: "Seu ChatGPT parece genérico porque ainda não conhece você.", text: "Aprenda, passo a passo e sem programação, a criar um GPT com seu contexto, sua personalidade, seu tom de voz e seus objetivos — para receber respostas muito mais alinhadas sem precisar explicar tudo novamente.", resultado: "RESULTADO: SUA MENTE DIGITAL CRIADA." },
  { step: "02", name: "El Espejo Digital", tag: "BÔNUS", icon: Eye, title: "E se a IA já tivesse percebido algo sobre você que você ainda não percebeu?", text: "Use prompts guiados para observar padrões presentes nas suas conversas, reconhecer forças, possíveis bloqueios, formas de decisão e oportunidades que podem estar passando despercebidas.", resultado: "RESULTADO: UMA NOVA PERSPECTIVA SOBRE VOCÊ." },
  { step: "03", name: "Tu Segundo Cerebro", tag: "PENSA", icon: Lightbulb, title: "Sua cabeça tem ideias demais e clareza de menos?", text: "Use comandos mestres prontos para copiar e aplicar dentro do ChatGPT para organizar pensamentos, desenvolver ideias, analisar decisões, encontrar pontos cegos e transformar objetivos em planos concretos.", resultado: "RESULTADO: UMA INTELIGÊNCIA QUE PENSA COM VOCÊ." },
  { step: "04", name: "Tu Gemelo Digital", tag: "MULTIPLICA", icon: Video, title: "Crie uma vez. Apareça muitas vezes.", text: "Aprenda um processo rápido e surpreendentemente fácil para transformar textos em vídeos com avatar e voz — mesmo que você não goste de gravar, tenha pouco tempo ou nunca tenha editado um vídeo.", resultado: "RESULTADO: SUAS IDEIAS GANHAM VOZ, IMAGEM E PRESENÇA." },
];
const resultados = [
  { icon: Brain, title: "Uma IA que conhece você", text: "Chega de respostas genéricas: a IA entende seu contexto e responde no seu idioma mental." },
  { icon: Lightbulb, title: "Ideias que se multiplicam", text: "Uma única ideia vira ângulos, formatos e oportunidades que sozinho você não teria visto." },
  { icon: Target, title: "Decisões com critério", text: "Analise riscos, prioridades e pontos cegos antes de agir. Menos dúvida, mais avanço." },
  { icon: Layers3, title: "Mente organizada", text: "Informação dispersa se transforma em estruturas claras, prontas para executar." },
  { icon: MessageSquareText, title: "Conteúdo sem atrito", text: "Do pensamento ao roteiro, ao post, à mensagem: você publica mais com menos esforço." },
  { icon: Video, title: "Vídeos sem se gravar", text: "Seu avatar e sua voz trabalham por você. Multiplique sua presença sem multiplicar seu tempo." },
  { icon: Gauge, title: "Execução 10 vezes mais rápida", text: "A distância entre pensar uma ideia e lançá-la cai para minutos, não semanas." },
  { icon: Eye, title: "Ver o que outros não veem", text: "Perguntas melhores, padrões claros, oportunidades que antes passavam despercebidas." },
];
const recursos = ["Perfil Mestre", "Prompt Mestre", "Comandos de Alto Valor", "Sistema de Decisões", "Planos de Ação", "Análise de Riscos", "Avatar com IA", "Voz com IA", "Roteiros para Vídeo", "Prompts de Reflexão", "Mapa de Pontos Fortes", "Perguntas de Evolução"];
const perguntas = [["Preciso saber programar?", "Não. O método foi desenhado para ser aplicado sem programação e sem conhecimento técnico avançado de prompts. Se você sabe escrever uma mensagem, consegue aplicar."], ["Preciso de experiência com inteligência artificial?", "Não. Você pode começar do zero e avançar seguindo o passo a passo de cada guia."], ["O método funciona com o ChatGPT?", "Sim. Tu Mente en GPT e Tu Segundo Cerebro foram criados para usar o ChatGPT como base de trabalho, e os princípios se aplicam a qualquer IA de texto."], ["Posso aplicar no meu negócio?", "Sim. O sistema serve para organizar ideias, criar conteúdo, analisar decisões, planejar projetos e transformar conhecimento em execução."], ["Preciso saber editar vídeos?", "Não é necessário dominar edição avançada. Tu Gemelo Digital simplifica a produção com ferramentas de inteligência artificial."], ["Como recebo o acesso?", "Depois da confirmação do pagamento, o acesso é entregue de forma digital pela plataforma de compra. Você começa em minutos."], ["O pagamento é único?", "Sim, a oferta desta página é de pagamento único. As condições finais são confirmadas no checkout seguro antes de finalizar a compra."], ["Como funciona a garantia de 7 dias?", "Você tem 7 dias para conhecer o método por dentro. Se decidir que não é para você, solicita a garantia dentro do prazo segundo as condições da plataforma de compra."]];

function MatrixRain() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return; const ctx = canvas.getContext("2d"); if (!ctx) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    let raf = 0, last = 0; const fontSize = 16; const chars = "アイウエオカキクケコサシスセソ01<>[]{}#$%&"; let drops: number[] = [];
    const resize = () => { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; drops = Array.from({ length: Math.ceil(canvas.width / fontSize) }, () => Math.floor(Math.random() * -50)); };
    resize(); window.addEventListener("resize", resize);
    const draw = (t: number) => { raf = requestAnimationFrame(draw); if (t - last < 78) return; last = t; ctx.fillStyle = "rgba(6, 10, 24, 0.2)"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.font = `${fontSize}px "Share Tech Mono", monospace`; drops.forEach((y, i) => { const ch = chars[Math.floor(Math.random() * chars.length)] ?? "0"; ctx.fillStyle = Math.random() > 0.975 ? "rgba(191, 219, 254, 0.5)" : "rgba(96, 165, 250, 0.22)"; ctx.fillText(ch, i * fontSize, y * fontSize); drops[i] = y * fontSize > canvas.height && Math.random() > 0.975 ? 0 : y + 1; }); };
    raf = requestAnimationFrame(draw); return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", resize); };
  }, []);
  return <canvas ref={ref} aria-hidden className="upsell-matrix pointer-events-none absolute inset-0 h-full w-full opacity-60" />;
}
function TituloSecao({ etiqueta, titulo, light = false, children }: { etiqueta: string; titulo: ReactNode; light?: boolean; children?: ReactNode }) { return <div className="mx-auto max-w-3xl text-center"><div className={`upsell-eyebrow mb-4 text-xs tracking-[0.28em] uppercase ${light ? "text-upsell-light-blue" : "text-upsell-blue"}`}>{etiqueta}</div><h2 className={`text-3xl font-bold tracking-[-0.01em] sm:text-4xl md:text-5xl ${light ? "text-upsell-light-text" : "text-white"}`}>{titulo}</h2>{children ? <div className={`mt-5 text-base leading-7 sm:text-lg ${light ? "text-upsell-light-muted" : "text-upsell-text-muted"}`}>{children}</div> : null}</div>; }
function CTA({ children = "QUERO CRIAR MINHA IA PERSONALIZADA", href = "#oferta" }: { children?: ReactNode; href?: string }) { return <a href={href} className="upsell-cta inline-flex w-full max-w-xl items-center justify-center gap-2 whitespace-nowrap rounded-2xl px-4 py-5 text-center text-xs tracking-wide text-white uppercase sm:gap-3 sm:px-6 sm:text-base">{children}<ArrowRight className="h-5 w-5 shrink-0" /></a>; }
function CapaCard({ cover, nome }: { cover: { url: string }; nome: string }) { return <div className="w-[220px] shrink-0 overflow-hidden rounded-[24px] p-1 sm:w-[280px]"><img src={cover.url} alt={`Capa ${nome}`} className="h-[240px] w-full rounded-[18px] object-cover sm:h-[290px]" /></div>; }
function DepoimentoCard({ imagem, index }: { imagem: { url: string }; index: number }) { return <div className="w-[240px] shrink-0 overflow-hidden rounded-[20px] p-1 sm:w-[300px]"><img src={imagem.url} alt={`Depoimento de cliente ${index + 1}`} className="h-auto w-full rounded-[14px] object-contain" /></div>; }
const compradores = ["Mariana S.", "Carlos P.", "Fernanda L.", "João M.", "Ana Paula R.", "Ricardo T.", "Camila V.", "Diego A.", "Patrícia G.", "Lucas H.", "Beatriz C.", "Thiago N."];
function NotificacoesVendas() { const [atual, setAtual] = useState(0); const [visivel, setVisivel] = useState(false); useEffect(() => { let ciclo: ReturnType<typeof setTimeout> | undefined; const timeouts: ReturnType<typeof setTimeout>[] = []; const mostrar = () => { setAtual(a => (a + 1) % compradores.length); setVisivel(true); timeouts.push(setTimeout(() => setVisivel(false), 4000)); ciclo = setTimeout(mostrar, 28000); }; const inicial = setTimeout(mostrar, 12000); return () => { clearTimeout(inicial); if (ciclo) clearTimeout(ciclo); timeouts.forEach(clearTimeout); }; }, []); return <div className={`fixed bottom-4 left-4 z-50 flex max-w-[290px] items-center gap-3 rounded-2xl bg-[#15803d] px-4 py-3 shadow-[0_18px_50px_-20px_rgba(34,197,94,0.65)] transition-opacity duration-200 ${visivel ? "opacity-100" : "opacity-0"}`} role="status"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-white/15 text-white"><BadgeCheck className="h-4 w-4" /></span><p className="text-xs leading-4 text-white"><span className="font-bold">{compradores[atual]}</span> adquiriu o <span className="font-semibold">Combo Método Mente Expandida</span></p></div>; }

export function TuGemeloDigitalPage() {
  return <main className="upsell-font overflow-hidden bg-upsell-bg text-upsell-text selection:bg-upsell-blue selection:text-white">
    <div className="border-b border-red-500/40 bg-gradient-to-r from-red-700 via-red-600 to-red-700 px-4 py-2.5 text-center text-[9px] font-bold leading-4 tracking-[0.08em] text-white uppercase sm:text-xs sm:tracking-[0.14em]">🔥 A oferta promocional está acabando!</div>

    {/* NOVA SEÇÃO 1 — MÉTODO COMPLETO, SEM PREÇO */}
    <section id="oferta-completa-topo" className="relative overflow-hidden border-b border-white/10 bg-black/25 px-5 py-14 sm:px-6 sm:py-20"><div className="pointer-events-none absolute left-1/2 top-1/2 h-[500px] w-[800px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-upsell-gold/10 blur-[150px]" /><div className="relative mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-gold/30 bg-upsell-gold/10 px-5 py-2 text-xs tracking-[0.18em] text-upsell-gold uppercase"><Sparkles className="h-4 w-4" /> Método Mente Expandida™</span><h1 className="mt-6 text-3xl font-bold tracking-[-0.01em] text-white sm:text-4xl md:text-5xl">Método Mente Expandida completo<span className="upsell-text-gradient-gold block">Os 4 guias em um único combo.</span></h1><p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-lg">Você recebe as quatro partes do método para personalizar o ChatGPT, pensar com mais clareza, reconhecer novos padrões e multiplicar sua presença digital.</p><img src={ofertaComboCompleto.url} alt="Método Mente Expandida completo com os quatro guias" className="mx-auto mt-9 w-full max-w-[340px] rounded-[28px] object-cover sm:max-w-md" /><div className="mx-auto mt-9 max-w-3xl grid gap-3 text-left sm:grid-cols-2">{comboItens.map(item => <div key={item.nome} className="rounded-2xl border border-white/10 bg-white/[0.045] px-5 py-4"><p className="font-bold text-white">{item.nome} <span className="ml-1 rounded-full bg-upsell-blue/20 px-2 py-0.5 text-[10px] font-bold tracking-wider text-upsell-blue uppercase">{item.etiqueta}</span></p><p className="mt-1 text-xs text-upsell-text-muted">{item.desc}</p></div>)}</div><p className="mx-auto mt-8 max-w-3xl text-sm leading-6 text-white/65 sm:text-base">Tu Mente en GPT — personalize o ChatGPT com seu contexto.<br />Tu Segundo Cerebro — pense com mais clareza dentro do ChatGPT.<br />Tu Gemelo Digital — transforme ideias em presença digital.<br />El Espejo Digital — reflexão guiada com o apoio do ChatGPT.</p></div></section>

    {/* SEÇÃO 2 — HERO ATUAL, MANTIDA */}
    <section className="relative overflow-hidden px-5 pb-12 pt-14 sm:px-6 sm:pb-16 sm:pt-20"><MatrixRain /><div className="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[720px] -translate-x-1/2 rounded-full bg-upsell-blue/15 blur-[140px]" /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-blue/25 bg-upsell-blue/10 px-4 py-2 text-[11px] tracking-[0.22em] text-upsell-blue uppercase sm:text-xs"><Sparkles className="h-4 w-4" /> Método Mente Expandida™</span><h2 className="mt-7 text-xl font-bold leading-[1.2] tracking-tight text-white sm:text-3xl md:text-4xl">DESCUBRA COMO EXTRAIR O MÁXIMO DO PODER DA INTELIGÊNCIA ARTIFICIAL E TRANSFORMÁ-LA EM UMA VERDADEIRA <span className="upsell-text-gradient-blue">MÁQUINA DE RESULTADOS PARA</span><span className="mt-1.5 block text-3xl font-extrabold tracking-wide sm:text-5xl md:text-6xl"><TypewriterWord /></span></h2><img src={heroCover.url} alt="Método Mente Expandida" className="mx-auto mt-8 w-full max-w-md rounded-[24px] shadow-[0_30px_90px_-30px_rgba(96,165,250,0.45)] sm:max-w-lg" /><p className="mx-auto mt-8 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-xl sm:leading-8">Seu ChatGPT parece genérico porque ainda não conhece você. Aprenda a criar uma inteligência personalizada com <span className="font-semibold text-white">seu contexto, sua identidade, seu tom de voz e seus objetivos</span> — e pare de explicar tudo de novo a cada conversa.</p><p className="mx-auto mt-5 max-w-3xl rounded-2xl border border-upsell-blue/25 bg-upsell-blue/[0.07] px-5 py-4 text-sm leading-6 text-white/80 sm:text-base">Sem programação, sem código e sem configurações complicadas. Siga o passo a passo, copie, adapte e comece a construir sua inteligência personalizada.</p><div className="mt-9 flex justify-center"><CTA /></div><div className="mt-5 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs font-semibold text-white/55 sm:text-sm"><span className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-upsell-success" /> Acesso digital imediato</span><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-upsell-success" /> Pagamento 100% seguro</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-upsell-success" /> 7 dias de garantia</span></div></div></div></section>

    <div className="upsell-marquee-mask border-y border-upsell-blue/30 bg-gradient-to-r from-blue-700 via-upsell-blue to-blue-700 py-3.5"><div className="upsell-marquee flex w-max items-center gap-8 px-4">{[...faixaItens, ...faixaItens, ...faixaItens, ...faixaItens].map((item, index) => <span key={index} className="upsell-eyebrow flex items-center gap-8 whitespace-nowrap text-xs tracking-[0.22em] text-white uppercase sm:text-sm">{item}<span className="text-white/50">◆</span></span>)}</div></div>

    <section className="border-b border-white/10 bg-white/[0.02] px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao etiqueta="O VERDADEIRO PROBLEMA" titulo={<>A IA já é brilhante.<br /><span className="upsell-text-gradient-blue">O problema é que ela não sabe quem você é.</span></>}>Cada dia usando IA sem um sistema, você paga um preço invisível: tempo, clareza e oportunidades. Veja se alguma dessas frases parece familiar demais:</TituloSecao><div className="mx-auto mt-8 grid max-w-5xl gap-4 md:grid-cols-2">{problemas.map(problema => <div key={problema} className="group flex items-center gap-4 rounded-2xl border border-red-500/40 bg-gradient-to-r from-red-600/20 to-red-500/[0.07] p-5 text-left shadow-[0_16px_50px_-25px_rgba(239,68,68,0.6)] sm:p-6"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-red-400/50 bg-red-500/25 text-red-300"><X className="h-5 w-5" /></span><p className="text-sm leading-6 font-bold text-red-100 sm:text-base">{problema}</p></div>)}</div><div className="mx-auto mt-10 flex max-w-4xl justify-center"><CTA /></div></div></section>

    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao light etiqueta="O SISTEMA" titulo={<>Cada guia funciona por conta própria.<br /><span className="text-upsell-light-blue">Juntos, eles ampliam todo o seu potencial.</span></>}>Você pode usar cada solução separadamente. Quando conecta as quatro, cada etapa complementa a próxima e transforma o ChatGPT em um sistema mais completo para <span className="font-semibold">conhecer, pensar, criar e multiplicar com você.</span></TituloSecao><div className="mt-10 grid gap-5 lg:grid-cols-2">{pilares.map(pilar => { const Icon = pilar.icon; return <article key={pilar.name} className="group relative overflow-hidden rounded-[30px] border border-upsell-light-border bg-upsell-light-surface p-7 text-center shadow-[0_24px_70px_-40px_rgba(30,58,138,0.35)] sm:p-9"><div className="relative flex flex-col items-center"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-upsell-light-blue/25 bg-upsell-light-blue/10 text-upsell-light-blue"><Icon className="h-6 w-6" /></div><div className="upsell-eyebrow mt-5 text-xs tracking-[0.2em] text-upsell-light-blue">{pilar.step} · {pilar.tag}</div><h3 className="mt-2 text-2xl font-bold text-upsell-light-text sm:text-3xl">{pilar.name}</h3><p className="mt-3 text-base font-semibold text-upsell-light-text/80">{pilar.title}</p><p className="mt-3 text-sm leading-7 text-upsell-light-muted sm:text-base">{pilar.text}</p><p className="upsell-eyebrow mt-4 text-[11px] tracking-[0.16em] text-upsell-light-blue uppercase">{pilar.resultado}</p></div></article>; })}</div><div className="mt-8 flex justify-center"><CTA /></div></div></section>

    <section id="tu-mente-en-gpt" className="border-y border-white/10 bg-white/[0.02] px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao etiqueta="TU MENTE EN GPT" titulo={<>Sua Mente Digital criada, <span className="upsell-text-gradient-blue">sem programar nada.</span></>}>Quantas vezes você já precisou explicar o que faz, quem é seu público, qual é seu objetivo e como deseja que o texto seja escrito? Você corrige o tom, troca palavras, acrescenta contexto e finalmente consegue uma resposta razoável. Mas, na conversa seguinte, tudo começa novamente.</TituloSecao><div className="mx-auto mt-8 max-w-4xl space-y-5 text-center text-base leading-7 text-upsell-text-muted sm:text-lg"><p>Tu Mente en GPT mostra como transformar o ChatGPT em uma inteligência personalizada, alimentada com sua identidade, seus conhecimentos, seus objetivos, suas referências e sua maneira de se comunicar.</p><p>Seguindo um processo visual, claro e fácil de implementar, você aprende a construir seu <span className="font-semibold text-white">Perfil Maestro</span>, criar as instruções do seu assistente, organizar seus arquivos de conhecimento e configurar um GPT que trabalhe com muito mais contexto desde o início.</p><p>Você não precisa programar, entender códigos ou dominar termos técnicos. O guia conduz cada etapa e entrega estruturas e prompts prontos para copiar, adaptar e utilizar.</p></div><div className="mx-auto mt-10 grid max-w-5xl gap-3 sm:grid-cols-2">{beneficiosMente.map(item => <div key={item} className="flex items-center gap-3 rounded-2xl border border-upsell-blue/20 bg-upsell-blue/[0.06] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-upsell-blue/15 text-upsell-blue"><Check className="h-4 w-4" /></span><p className="text-sm leading-6 text-white/85">{item}</p></div>)}</div></div></section>

    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao light etiqueta="EL ESPEJO DIGITAL · BÔNUS" titulo={<>Uma nova perspectiva <span className="text-upsell-light-blue">sobre você.</span></>}>E se a IA já tivesse percebido algo sobre você que você ainda não percebeu? Use prompts guiados para observar padrões presentes nas suas conversas, reconhecer forças, possíveis bloqueios, formas de decisão e oportunidades que podem estar passando despercebidas.</TituloSecao><div className="mx-auto mt-8 max-w-4xl text-center text-base leading-7 text-upsell-light-muted sm:text-lg">El Espejo Digital é uma ferramenta de reflexão guiada por IA. Suas respostas são baseadas nas informações disponibilizadas pelo usuário e não representam diagnóstico, terapia ou avaliação psicológica.</div><div className="mx-auto mt-10 grid max-w-5xl gap-3 sm:grid-cols-2">{beneficiosEspejo.map(item => <div key={item} className="flex items-center gap-3 rounded-2xl border border-upsell-light-border bg-upsell-light-surface p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-upsell-light-blue/10 text-upsell-light-blue"><Check className="h-4 w-4" /></span><p className="text-sm leading-6 text-upsell-light-text/85">{item}</p></div>)}</div></div></section>

    <section className="py-14 sm:py-20"><div className="px-5 sm:px-6"><div className="mx-auto max-w-3xl text-center"><div className="upsell-eyebrow mb-4 text-xs tracking-[0.28em] text-upsell-gold uppercase">VEJA O MÉTODO GANHANDO VIDA</div><h2 className="text-3xl font-bold text-white sm:text-4xl">É simples assim: qualquer pessoa consegue usar,<br className="hidden sm:block" /> <span className="upsell-text-gradient-blue">de onde estiver, direto no ChatGPT.</span></h2></div></div><div className="upsell-marquee-mask mt-10 overflow-hidden"><div className="upsell-marquee flex w-max items-center gap-5 px-5">{[...pilarImagens, ...pilarImagens, ...pilarImagens].map((cover, index) => <CapaCard key={index} cover={cover} nome="Método Mente Expandida" />)}</div></div><div className="px-5 sm:px-6"><div className="mx-auto mt-10 max-w-3xl text-center"><div className="upsell-eyebrow mb-4 text-xs tracking-[0.28em] text-upsell-gold uppercase">DEPOIMENTOS</div><h3 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">Quem já aplicou o método nunca mais usou a IA da mesma forma.</h3></div></div><div className="upsell-marquee-mask mt-10 overflow-hidden"><div className="upsell-marquee-reverse flex w-max items-center gap-5 px-5">{[...depoimentos, ...depoimentos].map((item, index) => <DepoimentoCard key={index} imagem={item} index={index % depoimentos.length} />)}</div></div><div className="mt-10 flex justify-center px-5 sm:px-6"><CTA /></div></section>

    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao light etiqueta="NA PRÁTICA" titulo={<>É isso que muda <span className="text-upsell-light-blue">desde o primeiro dia.</span></>} /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{resultados.map(({ icon: Icon, title, text }) => <article key={title} className="flex flex-col items-center rounded-[24px] border border-upsell-light-border bg-upsell-light-surface p-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-xl bg-upsell-light-blue/10 text-upsell-light-blue"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-bold text-upsell-light-text">{title}</h3><p className="mt-2 text-sm leading-6 text-upsell-light-muted">{text}</p></article>)}</div></div></section>

    <section className="py-14 sm:py-20"><div className="px-5 sm:px-6"><TituloSecao etiqueta="RECURSOS" titulo={<>Tudo organizado para você <span className="upsell-text-gradient-blue">aplicar o método.</span></>}>12 recursos prontos para usar, criados para você aplicar o método sem teoria desnecessária:</TituloSecao></div><div className="upsell-marquee-mask mt-12 overflow-hidden"><div className="upsell-marquee-reverse flex w-max gap-3 px-4">{[...recursos, ...recursos].map((recurso, index) => <div key={`${recurso}-${index}`} className="flex min-w-[230px] items-center gap-3 rounded-2xl bg-white/[0.035] px-5 py-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-upsell-blue/10 text-upsell-blue"><Check className="h-4 w-4" /></div><span className="text-sm font-semibold text-white/85">{recurso}</span></div>)}</div></div></section>

    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><TituloSecao light etiqueta="IMAGINE TER ISSO" titulo={<>Imagine abrir o chat e a IA <span className="text-upsell-light-blue">já saber do que você está falando.</span></>}>É isso que você vai poder pedir à sua inteligência digital, sem explicar nada de novo:</TituloSecao><div className="mx-auto mt-8 grid max-w-5xl gap-4">{["Analise esta decisão levando em conta meus objetivos, minha forma de pensar e todo o contexto que você já conhece sobre mim.", "Tenho esta ideia. Expanda, encontre as oportunidades que não estou vendo e transforme em um plano de ação.", "Transforme este conteúdo em um roteiro claro para o meu avatar digital e adapte a mensagem para um vídeo curto.", "Faça as perguntas necessárias para identificar qual padrão está influenciando esta decisão."].map((prompt, index) => <div key={prompt} className="flex gap-4 rounded-[24px] border border-upsell-light-border bg-upsell-light-surface p-5 sm:p-6"><div className="upsell-eyebrow grid h-10 w-10 shrink-0 place-items-center rounded-full bg-upsell-light-blue/10 text-xs text-upsell-light-blue">0{index + 1}</div><p className="text-sm leading-7 text-upsell-light-text/85 sm:text-base">“{prompt}”</p></div>)}</div></div></section>

    {/* SEGUNDA SESSÃO DA OFERTA — COM PREÇO */}
    <section id="combo" className="relative border-y border-white/10 bg-black/25 px-5 py-14 sm:px-6 sm:py-20"><div className="pointer-events-none absolute left-1/2 top-1/2 h-[520px] w-[820px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-upsell-gold/10 blur-[150px]" /><div className="relative mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-gold/30 bg-upsell-gold/10 px-5 py-2 text-xs tracking-[0.18em] text-upsell-gold uppercase"><Sparkles className="h-4 w-4" /> Valor promocional por tempo limitado</span><h2 className="mt-6 text-3xl font-bold tracking-[-0.01em] text-white sm:text-4xl md:text-5xl">Método Mente Expandida completo<span className="upsell-text-gradient-gold block">Os 4 guias em um único combo.</span></h2><p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-lg">Você recebe as quatro partes do método para personalizar o ChatGPT, pensar com mais clareza, reconhecer novos padrões e multiplicar sua presença digital.</p><img src={ofertaComboCompleto.url} alt="Combo Método Mente Expandida com os 4 guias" className="mx-auto mt-10 w-full max-w-[340px] rounded-[28px] object-cover sm:max-w-md" /><div className="mx-auto mt-10 max-w-3xl overflow-hidden rounded-[32px] border border-upsell-gold/30 bg-white/[0.045] text-left shadow-[0_25px_100px_-40px_rgba(250,204,21,0.35)]"><div className="grid gap-3 p-5 sm:p-8">{comboItens.map(item => <div key={item.nome} className="rounded-2xl border border-white/10 bg-white/[0.04] px-5 py-4"><p className="font-bold text-white">{item.nome} <span className="ml-1 rounded-full bg-upsell-blue/20 px-2 py-0.5 text-[10px] font-bold tracking-wider text-upsell-blue uppercase">{item.etiqueta}</span></p><p className="mt-1 text-xs text-upsell-text-muted">{item.desc}</p></div>)}</div><div className="mx-5 mb-5 rounded-2xl border border-white/10 bg-black/30 p-5 text-center sm:mx-8 sm:mb-8 sm:p-7"><p className="upsell-eyebrow text-xs tracking-[0.22em] text-upsell-gold uppercase">valor único pelo combo completo</p><div className="mt-2 text-4xl font-bold whitespace-nowrap text-upsell-success min-[360px]:text-5xl sm:text-7xl">US$ 20</div><div className="mt-7 flex justify-center"><CTA href="#combo">QUERO LEVAR O MÉTODO COMPLETO POR US$ 20</CTA></div><div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs font-semibold text-white/55"><span className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-upsell-success" /> Acesso imediato</span><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-upsell-success" /> Pagamento 100% seguro</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-upsell-success" /> Garantia de 7 dias</span></div></div></div></div></section>

    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-4xl text-center"><div className="relative mx-auto grid h-56 w-56 place-items-center rounded-full border-2 border-upsell-success/50 bg-upsell-success/10 text-center sm:h-64 sm:w-64"><div className="absolute inset-3 rounded-full border border-dashed border-upsell-success/40" /><div><BadgeCheck className="mx-auto h-10 w-10 text-upsell-success" /><div className="mt-1 text-6xl font-bold leading-none text-upsell-light-text">7</div><div className="upsell-eyebrow mt-1 text-xs tracking-[0.24em] text-upsell-light-text/70">DIAS</div><div className="mt-2 text-[10px] font-bold tracking-[0.2em] text-upsell-success uppercase">Garantia total</div></div></div><div className="mt-10"><div className="upsell-eyebrow text-xs tracking-[0.22em] text-upsell-success uppercase">RISCO ZERO PARA VOCÊ</div><h2 className="mt-4 text-4xl font-bold text-upsell-light-text sm:text-5xl">Teste por 7 dias. O risco fica todo com a gente.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-upsell-light-muted sm:text-lg">Entre, aplique o método e veja os resultados com seus próprios olhos. Se em 7 dias decidir que não é para você, basta solicitar a garantia segundo as condições da plataforma de compra.</p></div></div></section>

    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-4xl"><TituloSecao light etiqueta="PERGUNTAS FREQUENTES" titulo="O último passo antes de começar." /><div className="mt-12 space-y-3">{perguntas.map(([pergunta, resposta]) => <details key={pergunta} className="group rounded-2xl border border-upsell-light-border bg-upsell-light-surface p-5 open:border-upsell-light-blue/40"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-upsell-light-text"><span>{pergunta}</span><ChevronDown className="h-5 w-5 shrink-0 text-upsell-light-blue transition group-open:rotate-180" /></summary><p className="mt-4 pr-6 text-sm leading-7 text-upsell-light-muted sm:text-base">{resposta}</p></details>)}</div><div className="mt-10 flex justify-center"><CTA>QUERO COMEÇAR COM O MÉTODO</CTA></div></div></section>

    <NotificacoesVendas />
    <footer className="border-t border-white/10 px-5 py-8 text-center text-xs text-white/35 sm:px-6"><div className="upsell-eyebrow tracking-[0.18em] text-white/55">MÉTODO MENTE EXPANDIDA™</div><p className="mt-3">Produto digital. Os resultados dependem da aplicação individual do método e das ferramentas utilizadas.</p></footer>
  </main>;
}
